name: Call API Every 14 Minutes

on:
  schedule:
    # Runs every 6.9 minutes
    - cron: "*/6.9 * * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Don't Die Bro
        run: |
          curl -X GET https://hangman-db4p.onrender.com
