name: Ping Her Every 14 minutes

on:
  schedule:
    # Runs every (6.9 + 0.1)*2  minutes
    - cron: "*/14 * * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Don't Die Bro
        run: |
          curl -X GET https://comuniq.onrender.com
          sleep 10

      # - name: Check out the repository to the runner
      #   uses: actions/checkout@v4
      # - name: Run her script
      #   run: ./scripts/pingHer.sh
